project:
  type: website
  output-dir: docs

website:
  site-url: https://themisefth.com
  description: "The official website of Themis N. Efthimiou, Postdoctoral Researcher at the University of Edinburgh, specialising in social and cognitive neuroscience."
  page-footer: 
    left: "Email me at themiefth@ed.ac.uk"
  title: "Themis N. Efthimiou"
  favicon: /favicon.ico
  
  open-graph:
    locale: en_UK
    
  twitter-card: 
    creator: "@ThemisEfth"
    image: /website_banner.png

  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - href: content/blog.qmd
        text: Blog
      - href: content/publications.qmd
        text: Publications
      - href: content/cv.qmd
        text: CV
      - href: content/software.qmd
        text: Software
      - href: content/conferences.qmd
        text: Conferences
    right: 
      - icon: github
        href: https://github.com/ThemisEfth
      - icon: twitter
        href: https://x.com/ThemisEfth
      - icon: square-fill
        href: https://bsky.app/profile/themisefth.bsky.social
    background: primary

format:
  html:
    theme: 
      light: pulse
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
    toggle: true 
    allow-html: true
editor: visual