project:
  type: website
  output-dir: docs

website:
  site-url: https://themisefth.com
  description: "The personal website of Themis N. Efthimiou, a quantitative researcher focused on applying data science to social and behavioural questions."
  title: "Themis N. Efthimiou"
  favicon: /favicon.ico
  
  open-graph:
    locale: en_UK
    
  twitter-card: 
    creator: "@ThemisEfth"
    image: /website_banner.png

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: content/blog.qmd
        text: Blog
      - href: content/publications.qmd
        text: Publications
      - href: content/cv.qmd
        text: CV
      - href: content/software.qmd
        text: Software
      - href: content/conferences.qmd
        text: Conferences
    right: 
      - icon: github
        href: https://github.com/ThemisEfth
      - icon: twitter
        href: https://x.com/ThemisEfth
      - icon: square-fill
        href: https://bsky.app/profile/themisefth.bsky.social
    background: primary # This will use the primary colour defined in styles.scss

  page-footer: 
    left: "Contact: themiftw20@gmail.com"
    center: "© 2025 Themis N. Efthimiou" # Added a copyright year
    border: true

format:
  html:
    theme: 
      # Use the 'flatly' theme as a base and layer our custom SCSS file on top
      light: [flatly, styles.scss]
      dark: darkly
    css: styles.css # Keep your original CSS for any specific overrides
    toc: true
    toc-depth: 2
    code-fold: false
    code-tools: false
    toggle: true 
    allow-html: true

editor: visual